[package]
name = "bezel-zed-sum-tree"
version = "0.3.2+zed.d9ad6a"
readme = "README.md"
repository = "https://github.com/crabtalk/zed"
edition.workspace = true
license = "Apache-2.0"
description = "A sum tree data structure, a concurrency-friendly B-tree"

[lints]
workspace = true

[lib]
name = "sum_tree"
path = "src/sum_tree.rs"
doctest = false

[dependencies]
heapless.workspace = true
rayon.workspace = true
log.workspace = true
ztracing.workspace = true
tracing.workspace = true
proptest = { workspace = true, optional = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[features]
test-support = ["proptest"]