[package]
name = "bezel-zed-media"
version = "0.3.6+zed.d9ad6a"
readme = "README.md"
repository = "https://github.com/crabtalk/zed"
edition.workspace = true
license = "Apache-2.0"
description = "Bindings to macos media handling APIs for Zed"

[lints]
workspace = true

[lib]
name = "media"
path = "src/media.rs"
doctest = false

[dependencies]
anyhow.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation.workspace = true
foreign-types.workspace = true
metal.workspace = true
core-video.workspace = true
objc.workspace = true

[build-dependencies]
bindgen = "0.71"
