[package]
name = "bezel-zed-http-client"
version = "0.3.1+zed.d9ad6a"
readme = "README.md"
repository = "https://github.com/crabtalk/zed"
edition.workspace = true
license = "Apache-2.0"
description = "A HTTP client library for Zed and GPUI"

[lints]
workspace = true

[features]
test-support = []
github-download = []

[lib]
name = "http_client"
path = "src/http_client.rs"
doctest = true

[dependencies]
anyhow.workspace = true
async-compression.workspace = true
bytes.workspace = true
derive_more.workspace = true
futures.workspace = true
http-body.workspace = true
http.workspace = true
log.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
url.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-fs = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
