[package]
name = "bezel-zed-derive-refineable"
version = "0.3.0+zed.bc538d"
readme = "README.md"
repository = "https://github.com/crabtalk/zed"
edition.workspace = true
license = "Apache-2.0"
description = "A derive macro for creating refinement types in Rust"


[lints]
workspace = true

[lib]
name = "derive_refineable"
path = "src/derive_refineable.rs"
proc-macro = true
doctest = false

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
